<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Adrenth.HtmlPurifier plugin configuration
    |--------------------------------------------------------------------------
    |
    | For detailed information about each configuration parameter go to:
    | http://htmlpurifier.org/live/configdoc/plain.html
    |
    */

    'Attr.AllowedClasses' => null,
    'Attr.AllowedFrameTargets' => [],
    'Attr.AllowedRel' => [],
    'Attr.AllowedRev' => [],
    'Attr.ClassUseCDATA' => null,
    'Attr.DefaultImageAlt' => null,
    'Attr.DefaultInvalidImage' => '',
    'Attr.DefaultInvalidImageAlt' => 'Invalid image',
    'Attr.DefaultTextDir' => 'ltr',
    'Attr.EnableID' => false,
    'Attr.ForbiddenClasses' => [],
    'Attr.ID.HTML5' => null,
    'Attr.IDBlacklist' => [],
    'Attr.IDBlacklistRegexp' => null,
    'Attr.IDPrefix' => '',
    'Attr.IDPrefixLocal' => '',
    'AutoFormat.AutoParagraph' => false,
    'AutoFormat.Custom' => [],
    'AutoFormat.DisplayLinkURI' => false,
    'AutoFormat.Linkify' => false,
    'AutoFormat.PurifierLinkify.DocURL' => '#%s',
    'AutoFormat.PurifierLinkify' => false,
    'AutoFormat.RemoveEmpty.Predicate' => [
        'colgroup' => [],
        'th' => [],
        'td' => [],
        'iframe' => [
            0 => 'src',
        ],
    ],
    'AutoFormat.RemoveEmpty.RemoveNbsp.Exceptions' => [
        'td' => true,
        'th' => true,
    ],
    'AutoFormat.RemoveEmpty.RemoveNbsp' => false,
    'AutoFormat.RemoveEmpty' => false,
    'AutoFormat.RemoveSpansWithoutAttributes' => false,
    'CSS.AllowDuplicates' => false,
    'CSS.AllowImportant' => false,
    'CSS.AllowTricky' => false,
    'CSS.AllowedFonts' => null,
    'CSS.AllowedProperties' => null,
    'CSS.DefinitionRev' => 1,
    'CSS.ForbiddenProperties' => [],
    'CSS.MaxImgLength' => '1200px',
    'CSS.Proprietary' => false,
    'CSS.Trusted' => false,
    'Cache.DefinitionImpl' => 'Serializer',
    'Cache.SerializerPath' => temp_path(),
    'Cache.SerializerPermissions' => 493,
    'Core.AggressivelyFixLt' => true,
    'Core.AggressivelyRemoveScript' => true,
    'Core.AllowHostnameUnderscore' => false,
    'Core.CollectErrors' => false,
    'Core.ColorKeywords' => [
        'maroon' => '#800000',
        'red' => '#FF0000',
        'orange' => '#FFA500',
        'yellow' => '#FFFF00',
        'olive' => '#808000',
        'purple' => '#800080',
        'fuchsia' => '#FF00FF',
        'white' => '#FFFFFF',
        'lime' => '#00FF00',
        'green' => '#008000',
        'navy' => '#000080',
        'blue' => '#0000FF',
        'aqua' => '#00FFFF',
        'teal' => '#008080',
        'black' => '#000000',
        'silver' => '#C0C0C0',
        'gray' => '#808080',
    ],
    'Core.ConvertDocumentToFragment' => true,
    'Core.DirectLexLineNumberSyncInterval' => 0,
    'Core.DisableExcludes' => false,
    'Core.EnableIDNA' => false,
    'Core.Encoding' => 'utf-8',
    'Core.EscapeInvalidChildren' => false,
    'Core.EscapeInvalidTags' => false,
    'Core.EscapeNonASCIICharacters' => false,
    'Core.HiddenElements' => [
        'script' => true,
        'style' => true,
    ],
    'Core.Language' => 'en',
    'Core.LegacyEntityDecoder' => false,
    'Core.LexerImpl' => null,
    'Core.MaintainLineNumbers' => null,
    'Core.NormalizeNewlines' => true,
    'Core.RemoveInvalidImg' => true,
    'Core.RemoveProcessingInstructions' => false,
    'Core.RemoveScriptContents' => null,
    'Filter.Custom' => [],
    'Filter.ExtractStyleBlocks.Escaping' => true,
    'Filter.ExtractStyleBlocks.Scope' => null,
    'Filter.ExtractStyleBlocks.TidyImpl' => null,
    'Filter.ExtractStyleBlocks' => false,
    'Filter.YouTube' => false,
    'HTML.Allowed' => null,
    'HTML.AllowedAttributes' => null,
    'HTML.AllowedComments' => [],
    'HTML.AllowedCommentsRegexp' => null,
    'HTML.AllowedElements' => null,
    'HTML.AllowedModules' => null,
    'HTML.Attr.Name.UseCDATA' => false,
    'HTML.BlockWrapper' => 'p',
    'HTML.CoreModules' => [
        'Structure' => true,
        'Text' => true,
        'Hypertext' => true,
        'List' => true,
        'NonXMLCommonAttributes' => true,
        'XMLCommonAttributes' => true,
        'CommonAttributes' => true,
    ],
    'HTML.CustomDoctype' => null,
    'HTML.DefinitionID' => null,
    'HTML.DefinitionRev' => 1,
    'HTML.Doctype' => null,
    'HTML.FlashAllowFullScreen' => false,
    'HTML.ForbiddenAttributes' => [],
    'HTML.ForbiddenElements' => [],
    'HTML.MaxImgLength' => 1200,
    'HTML.Nofollow' => false,
    'HTML.Parent' => 'div',
    'HTML.Proprietary' => false,
    'HTML.SafeEmbed' => false,
    'HTML.SafeIframe' => false,
    'HTML.SafeObject' => false,
    'HTML.SafeScripting' => [],
    'HTML.Strict' => false,
    'HTML.TargetBlank' => false,
    'HTML.TargetNoopener' => true,
    'HTML.TargetNoreferrer' => true,
    'HTML.TidyAdd' => [],
    'HTML.TidyLevel' => 'medium',
    'HTML.TidyRemove' => [],
    'HTML.Trusted' => false,
    'HTML.XHTML' => true,
    'Output.CommentScriptContents' => true,
    'Output.FixInnerHTML' => true,
    'Output.FlashCompat' => false,
    'Output.Newline' => null,
    'Output.SortAttr' => false,
    'Output.TidyFormat' => false,
    'Test.ForceNoIconv' => false,
    'URI.AllowedSchemes' => [
        'http' => true,
        'https' => true,
        'mailto' => true,
        'ftp' => true,
        'nntp' => true,
        'news' => true,
        'tel' => true,
    ],
    'URI.Base' => null,
    'URI.DefaultScheme' => 'http',
    'URI.DefinitionID' => null,
    'URI.DefinitionRev' => 1,
    'URI.Disable' => false,
    'URI.DisableExternal' => false,
    'URI.DisableExternalResources' => false,
    'URI.DisableResources' => false,
    'URI.Host' => null,
    'URI.HostBlacklist' => [],
    'URI.MakeAbsolute' => false,
    'URI.Munge' => null,
    'URI.MungeResources' => false,
    'URI.MungeSecretKey' => null,
    'URI.OverrideAllowedSchemes' => true,
    'URI.SafeIframeRegexp' => null,
];
